---
Name: event-tickets-app
After: 'event-tickets/*'
---
Member:
  extensions:
    - 'Broarm\EventTickets\App\TicketScannerExtension'

Director:
  rules:
    'eventtickets/authenticator': 'Broarm\EventTickets\App\Authenticator'
    'eventtickets/authenticator/validatetoken': 'Broarm\EventTickets\App\Authenticator'
    'eventtickets/validate': 'Broarm\EventTickets\App\TicketValidator'
