---
Name: event-tickets-app
After: 'event-tickets/*'
---
SiteConfig:
  extensions:
    - 'Broarm\EventTickets\TicketScannerExtension'

Director:
  rules:
    'validateticket': 'Broarm\EventTickets\TicketValidator'